import type { EquipmentMetadata } from "./equipment.type";

const EQUIPMENT_LIST: EquipmentMetadata[] = [
  {
    name: "命運武器",
    subcategory: "destiny-weapon",
    category: "weapon",
    features: ["mainPot", "additionalPot", "soul"],
    commonLevels: [250],
    isFixedLevel: true,
  },
  {
    name: "武器",
    subcategory: "primary-weapon",
    category: "weapon",
    features: ["mainPot", "additionalPot", "soul"],
    commonLevels: [160, 200],
    isFixedLevel: false,
  },
  {
    name: "副武器",
    subcategory: "secondary-weapon",
    category: "weapon",
    features: ["mainPot", "additionalPot"],
    commonLevels: [100, 130, 140],
    isFixedLevel: false,
  },
  {
    name: "副武器(力量之盾、靈魂戒指)",
    subcategory: "secondary-weapon-other",
    category: "weapon",
    features: ["mainPot", "additionalPot"],
    commonLevels: [100, 140],
    isFixedLevel: false,
  },
  // {
  //   name: "盾牌",
  //   subcategory: "shield",
  //   category: "weapon",
  //   features: ["mainPot", "additionalPot"],
  //   commonLevels: [130],
  //   isFixedLevel: false,
  // },
  {
    name: "能源",
    subcategory: "emblem",
    category: "weapon",
    features: ["mainPot", "additionalPot"],
    commonLevels: [100, 200],
    isFixedLevel: false,
  },
  {
    name: "帽子",
    subcategory: "hat",
    category: "armor",
    features: ["mainPot", "additionalPot"],
    commonLevels: [160, 200, 250],
    isFixedLevel: false,
  },
  {
    name: "套服",
    subcategory: "overall",
    category: "armor",
    features: ["mainPot", "additionalPot"],
    commonLevels: [170],
    isFixedLevel: false,
  },
  {
    name: "上衣",
    subcategory: "top",
    category: "armor",
    features: ["mainPot", "additionalPot"],
    commonLevels: [250],
    isFixedLevel: false,
  },
  {
    name: "下褲",
    subcategory: "bottom",
    category: "armor",
    features: ["mainPot", "additionalPot"],
    commonLevels: [250],
    isFixedLevel: false,
  },
  {
    name: "鞋子",
    subcategory: "shoes",
    category: "armor",
    features: ["mainPot", "additionalPot"],
    commonLevels: [160, 200, 250],
    isFixedLevel: false,
  },
  {
    name: "手套",
    subcategory: "gloves",
    category: "armor",
    features: ["mainPot", "additionalPot"],
    commonLevels: [160, 200, 250],
    isFixedLevel: false,
  },
  {
    name: "披風",
    subcategory: "cape",
    category: "armor",
    features: ["mainPot", "additionalPot"],
    commonLevels: [160, 200, 250],
    isFixedLevel: false,
  },
  {
    name: "肩膀",
    subcategory: "shoulder",
    category: "accessory",
    features: ["mainPot", "additionalPot"],
    commonLevels: [160, 200, 250],
    isFixedLevel: false,
  },
  {
    name: "腰帶",
    subcategory: "belt",
    category: "accessory",
    features: ["mainPot", "additionalPot"],
    commonLevels: [150, 200],
    isFixedLevel: false,
  },
  {
    name: "戒指",
    subcategory: "ring",
    category: "accessory",
    features: ["mainPot", "additionalPot"],
    commonLevels: [150, 160, 250],
    isFixedLevel: false,
  },
  {
    name: "項鍊",
    subcategory: "pendant",
    category: "accessory",
    features: ["mainPot", "additionalPot"],
    commonLevels: [150, 160, 250],
    isFixedLevel: false,
  },
  {
    name: "耳環",
    subcategory: "earrings",
    category: "accessory",
    features: ["mainPot", "additionalPot"],
    commonLevels: [150, 160, 200],
    isFixedLevel: false,
  },
  {
    name: "臉飾",
    subcategory: "face",
    category: "accessory",
    features: ["mainPot", "additionalPot"],
    commonLevels: [160],
    isFixedLevel: false,
  },
  {
    name: "眼飾",
    subcategory: "eye",
    category: "accessory",
    features: ["mainPot", "additionalPot"],
    commonLevels: [160],
    isFixedLevel: false,
  },

  {
    name: "胸章",
    subcategory: "badge",
    category: "other",
    features: ["mainPot", "additionalPot"],
    commonLevels: [10],
    isFixedLevel: false,
  },
  {
    name: "機器心臟",
    subcategory: "heart",
    category: "other",
    features: ["mainPot", "additionalPot"],
    commonLevels: [150, 160, 200],
    isFixedLevel: false,
  },
];

export const EQUIPMENT_METADATA_MAP = new Map<string, EquipmentMetadata>(
  EQUIPMENT_LIST.map((equip) => [equip.subcategory, equip]),
);

export default EQUIPMENT_LIST;
