import type { EquipmentMetadata } from "./equipment.type";

const EQUIPMENT_LIST: EquipmentMetadata[] = [
  {
    name: "命運武器",
    subcategory: "destiny-weapon",
    category: "weapon",
    commonLevels: [250],
    isFixedLevel: true,
    baseStats: { attack: 100 }, // 預設值，實際由各裝備 JSON 決定
  },
  {
    name: "武器",
    subcategory: "primary-weapon",
    category: "weapon",
    commonLevels: [160, 200],
    isFixedLevel: false,
    baseStats: { attack: 100 },
  },
  {
    name: "副武器",
    subcategory: "secondary-weapon",
    category: "weapon",
    commonLevels: [100, 130, 140],
    isFixedLevel: false,
    baseStats: { attack: 10 },
  },
  {
    name: "副武器(力量之盾、靈魂戒指)",
    subcategory: "secondary-weapon-other",
    category: "weapon",
    commonLevels: [100, 140],
    isFixedLevel: false,
    baseStats: { defense: 10 },
  },
  {
    name: "能源",
    subcategory: "emblem",
    category: "weapon",
    commonLevels: [100, 200],
    isFixedLevel: false,
    baseStats: { attack: 10 },
  },
  {
    name: "帽子",
    subcategory: "hat",
    category: "armor",
    commonLevels: [160, 200, 250],
    isFixedLevel: false,
    baseStats: { defense: 100 },
  },
  {
    name: "套服",
    subcategory: "overall",
    category: "armor",
    commonLevels: [170],
    isFixedLevel: false,
    baseStats: { defense: 200 },
  },
  {
    name: "上衣",
    subcategory: "top",
    category: "armor",
    commonLevels: [250],
    isFixedLevel: false,
    baseStats: { defense: 100 },
  },
  {
    name: "下褲",
    subcategory: "bottom",
    category: "armor",
    commonLevels: [250],
    isFixedLevel: false,
    baseStats: { defense: 100 },
  },
  {
    name: "鞋子",
    subcategory: "shoes",
    category: "armor",
    commonLevels: [160, 200, 250],
    isFixedLevel: false,
    baseStats: { defense: 100 },
  },
  {
    name: "手套",
    subcategory: "gloves",
    category: "armor",
    commonLevels: [160, 200, 250],
    isFixedLevel: false,
    baseStats: { defense: 100 },
  },
  {
    name: "披風",
    subcategory: "cape",
    category: "armor",
    commonLevels: [160, 200, 250],
    isFixedLevel: false,
    baseStats: { defense: 100 },
  },
  {
    name: "肩膀",
    subcategory: "shoulder",
    category: "accessory",
    commonLevels: [160, 200, 250],
    isFixedLevel: false,
    baseStats: { defense: 50 },
  },
  {
    name: "腰帶",
    subcategory: "belt",
    category: "accessory",
    commonLevels: [150, 200],
    isFixedLevel: false,
    baseStats: { defense: 50 },
  },
  {
    name: "戒指",
    subcategory: "ring",
    category: "accessory",
    commonLevels: [150, 160, 250],
    isFixedLevel: false,
    baseStats: { allStat: 10 },
  },
  {
    name: "項鍊",
    subcategory: "pendant",
    category: "accessory",
    commonLevels: [150, 160, 250],
    isFixedLevel: false,
    baseStats: { allStat: 10 },
  },
  {
    name: "耳環",
    subcategory: "earrings",
    category: "accessory",
    commonLevels: [150, 160, 200],
    isFixedLevel: false,
    baseStats: { allStat: 10 },
  },
  {
    name: "臉飾",
    subcategory: "face",
    category: "accessory",
    commonLevels: [160],
    isFixedLevel: false,
    baseStats: { allStat: 10 },
  },
  {
    name: "眼飾",
    subcategory: "eye",
    category: "accessory",
    commonLevels: [160],
    isFixedLevel: false,
    baseStats: { allStat: 10 },
  },
  {
    name: "胸章",
    subcategory: "badge",
    category: "other",
    commonLevels: [10],
    isFixedLevel: false,
    baseStats: { allStat: 10 },
  },
  {
    name: "機器心臟",
    subcategory: "heart",
    category: "other",
    commonLevels: [150, 160, 200],
    isFixedLevel: false,
    baseStats: { allStat: 10 },
  },
];

export const EQUIPMENT_METADATA_MAP = new Map<string, EquipmentMetadata>(
  EQUIPMENT_LIST.map((equip) => [equip.subcategory, equip]),
);

export default EQUIPMENT_LIST;
